#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac


vol=$(pamixer --get-volume)


db=$(db-convert $vol)

if [ $vol -ge 50 ]
then
	icon="🔊"
elif [ $vol -eq 0 ]
then
	icon="🔇"
else
	icon="🔈"
fi

[ $(pamixer --get-mute) = true ] && icon="🔇"

echo $icon $db
